// <auto-generated />
namespace Server_API.Migrations.ApplicationUserMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialApplicationMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialApplicationMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201803161313288_Initial Application Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
